# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      # - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run Azure CLI commands"
        run: |
          az account show
          az group list
          pwd

  #     - name: docker login, build and push
  #       run: |
  #         az acr login -n ${{ secrets.ACR }}
  #         docker build ./target -t ${{ secrets.ACR }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
  #         docker push ${{ secrets.ACR }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
  #       env:
  #         IMAGE_NAME: scaffold

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: "production"
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: "tf-stg-app2"
  #         slot-name: "production"
  #         # publish-profile: ${{ secrets.AzureAppService_PublishProfile_1cf9a08885374cfeb0551b41fc49cab6 }}
  #         images: "epaasrepo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aec737c58fff40c4ae557713063af83f }}/scaffold:${{ github.sha }}"
